### ISSUE TITLE
Convert ISession to typealias of String

### ISSUE THREAD

**Issue by TarasMazepa** [vitkhudenko/session_tracker#3]
Technically you do not need to have whole interface for ISession. It makes sense to introduce typealias instead - saving some bypecode :)
Before
```
interface ISession {
    val sessionId: String
}
```
After (also you can change name to SessionId)
```
typealias ISession = String
```

Also with this approach you can reduce one generic argument

**Comment by vitkhudenko** [comment]
Technically `SessionTracker` could just track a map of `String` (sessionId) to session state machine.

However, going one step further, I assume client apps will benefit from implementing `ISession` interface and adding additional fields to the implementation.

Also, with the current approach, other useful things are possible:
* `SessionTracker.getSessions()` returns a list of sessions (vs just list of session ids).
* `SessionTracker.Listener` is able to communicate session instances directly (vs just list of session id), e.g.:
    ```
        fun onSessionStateChanged(
            sessionTracker: SessionTracker<S, Event, State>,
            session: S,
            oldState: State,
            newState: State
        )
    ```

**Comment by TarasMazepa** [comment]
There is three ways how user can start using `ISession` interface:
1. Just hold session id
2. Hold session id and some extra fields but no logic
3. Hold hole session logic

In option #1 listener will need to retrieve true session from somewhere else in order to access additional information or perform actions on session
In option #2 listener will need to retrieve true session only for performing actions on the session, but will be required to add extra logic to the implementation of `ISessionTrackerStorage`
In option #3 listener will not need to retrieve true session to do any operation. But implementation of `ISessionTrackerStorage` will become much more complex as whole working session should be returned, this will have next problems:
* Include lazy initialization for sessions
* Decide which framework to load first (session tracker or session instantiation)

From my POV with current approach people will be lured more towards #3 with time, as this will save some time for them (by not retrieving true session from other storage), which will lead to problems described above :)

**Comment by vitkhudenko** [comment]
`ISession` is intended to be a data structure without session logic. I should have stated this in the documentation explicitly.

The "session logic" in the client apps could be one of the following:

1. A view model handles user actions, e.g. Login or Logout. With `SessionTracker` it is just calling `SessionTracker`'s API, e.g. trackSession()/untrackSession()/consumeEvent().
2. Activating/deactivating a session triggers creation/releasing of session specific scope of objects. That's what `SessionTracker.Listener` is for.
3. Processing session state changes (other than described in point 2). That's what `SessionTracker.Listener` is for.

That's basically all. IMO, there is no need to add any session logic to the `ISession` implementation.

**Comment by vitkhudenko** [comment]
On a second thought I'm under impression we are taking about different things.

**Comment by TarasMazepa** [comment]
> On a second thought I'm under impression we are taking about different things.

My point was that even if it is convenient to store extra information about session in `ISession` implementation, listeners will still need to retrieve real session from somewhere to execute some logic. 

So from that point of view there is no significant benefit in having extra metadata in `ISession`. And this can lead to introduction of business logic inside `ISession` (not saying that it is embraced by documentation, but this is path which could be taken; removing this possibility will not downgrade experience too much, but potentially can save from headache).

**Comment by vitkhudenko** [comment]
I have to think about this.

The funny thing is initially there was session ID only. But later I switched on the `ISession` interface, thinking it would probably be more convenient for clients to track a session data structure (vs just session ID), so the idea was to have `ISession` instances as real sessions (and `ISessionTrackerStorage` being sufficient to store real sessions).
